#!/usr/bin/env sh

mkdir -p deps
cd deps/

echo "Downloading Gatling ${GATLING_VERSION}"
VERSION=3.9.5
LINK=https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/$VERSION/gatling-charts-highcharts-bundle-$VERSION-bundle.zip

wget -O gatling.zip $LINK

unzip gatling.zip
rm gatling.zip
mv gatling-charts-highcharts-bundle-3.9.5 gatling
echo "All done!"
